// Code generated by sqlc-multi-db. DO NOT EDIT.
package database

import (
	"database/sql"
	"time"
)

type AddBookTagParams struct {
	BookID int64
	TagID  int64
}

type AddBookTagsParams struct {
	BookID []int64
	TagID  []int64
}

type Book struct {
	ID          int64
	Title       string
	Author      string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CreateBookParams struct {
	Title       string
	Author      string
	Description sql.NullString
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UpdateBookParams struct {
	Title       string
	Author      string
	Description sql.NullString
	ID          int64
}
