// Code generated by sqlc-multi-db. DO NOT EDIT.
package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	// AddBookTag adds a tag to a book.
	// INSERT INTO book_tags ("book_id", "tag_id") VALUES ($1, $2)
	AddBookTag(ctx context.Context, arg AddBookTagParams) error
	// AddBookTags adds multiple tags to a book.
	// INSERT INTO book_tags ("book_id", "tag_id") VALUES (unnest($1::bigint[]), unnest($2::bigint[]))
	// @bulk-for AddBookTag
	AddBookTags(ctx context.Context, arg AddBookTagsParams) error
	// CreateBook creates a new book.
	// INSERT INTO books ("title", "author", "description") VALUES ($1, $2, $3) RETURNING "id", "title", "author", "description", "created_at", "updated_at"
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	// CreateTag creates a new tag.
	// INSERT INTO tags ("name") VALUES ($1) RETURNING "id", "name", "created_at", "updated_at"
	CreateTag(ctx context.Context, name string) (Tag, error)
	// DeleteBook deletes a book by ID.
	// DELETE FROM books WHERE id = $1
	DeleteBook(ctx context.Context, id int64) error
	// GetBook retrieves a book by ID.
	// SELECT "id", "title", "author", "description", "created_at", "updated_at" FROM books WHERE id = $1
	GetBook(ctx context.Context, id int64) (Book, error)
	// GetBookByID (Synthetic)
	GetBookByID(ctx context.Context, id int64) (Book, error)
	// GetBookTags retrieves all tags for a book.
	// SELECT t."id", t."name", t."created_at", t."updated_at" FROM tags t INNER JOIN book_tags bt ON t.id = bt.tag_id WHERE bt.book_id = $1
	GetBookTags(ctx context.Context, bookID int64) ([]Tag, error)
	// GetBooksByAuthor retrieves all books by an author.
	// SELECT "id", "title", "author", "description", "created_at", "updated_at" FROM books WHERE author = $1
	GetBooksByAuthor(ctx context.Context, author string) ([]Book, error)
	// GetTag retrieves a tag by ID.
	// SELECT "id", "name", "created_at", "updated_at" FROM tags WHERE id = $1
	GetTag(ctx context.Context, id int64) (Tag, error)
	// GetTagByID (Synthetic)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	// ListBooks retrieves all books.
	// SELECT "id", "title", "author", "description", "created_at", "updated_at" FROM books ORDER BY title
	ListBooks(ctx context.Context) ([]Book, error)
	// UpdateBook updates a book.
	// UPDATE books SET "title" = $1, "author" = $2, "description" = $3, "updated_at" = NOW() WHERE id = $4 RETURNING "id", "title", "author", "description", "created_at", "updated_at"
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)

	WithTx(tx *sql.Tx) Querier
	DB() *sql.DB
}
