// Code generated by sqlc-multi-db. DO NOT EDIT.
package database

import "errors"

var (
	// ErrNotFound is returned when a query returns no rows.
	ErrNotFound = errors.New("not found")

	// ErrMismatchedSlices is returned when bulk operations receive slices of different lengths.
	ErrMismatchedSlices = errors.New("mismatched slice lengths")
)
