// Code generated by sqlc-multi-db. DO NOT EDIT.
package database

import (
	"context"
	"database/sql"
	"errors"

	"github.com/kalbasit/sqlc-multi-db/example/pkg/database/sqlitedb"
)

// sqliteWrapper wraps the sqlite adapter.
type sqliteWrapper struct {
	adapter *sqlitedb.Adapter
}

func (w *sqliteWrapper) AddBookTag(ctx context.Context, arg AddBookTagParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.AddBookTag(ctx, sqlitedb.AddBookTagParams{
		BookID: arg.BookID,
		TagID:  arg.TagID,
	})
}

func (w *sqliteWrapper) AddBookTags(ctx context.Context, arg AddBookTagsParams) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	if len(arg.TagID) != len(arg.BookID) {
		return ErrMismatchedSlices
	}
	for i, v := range arg.BookID {
		_ = i
		err := w.adapter.AddBookTag(ctx, sqlitedb.AddBookTagParams{
			BookID: v,

			TagID: arg.TagID[i],
		},
		)
		if err != nil {
			return err
		}
	}
	return nil
}

func (w *sqliteWrapper) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.CreateBook(ctx, sqlitedb.CreateBookParams{
		Title:       arg.Title,
		Author:      arg.Author,
		Description: arg.Description,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Book{}, ErrNotFound
		}

		return Book{}, err
	}

	// Convert Single Domain Struct

	return Book{
		ID: res.ID,

		Title: res.Title,

		Author: res.Author,

		Description: res.Description,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) CreateTag(ctx context.Context, name string) (Tag, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.CreateTag(ctx, name)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Tag{}, ErrNotFound
		}

		return Tag{}, err
	}

	// Convert Single Domain Struct

	return Tag{
		ID: res.ID,

		Name: res.Name,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) DeleteBook(ctx context.Context, id int64) error {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	return w.adapter.DeleteBook(ctx, id)
}

func (w *sqliteWrapper) GetBook(ctx context.Context, id int64) (Book, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetBook(ctx, id)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Book{}, ErrNotFound
		}

		return Book{}, err
	}

	// Convert Single Domain Struct

	return Book{
		ID: res.ID,

		Title: res.Title,

		Author: res.Author,

		Description: res.Description,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetBookByID(ctx context.Context, id int64) (Book, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	query := "SELECT \"id\", \"title\", \"author\", \"description\", \"created_at\", \"updated_at\" FROM books WHERE id = ?"
	row := w.adapter.DBTX().QueryRowContext(ctx, query, id)
	var res sqlitedb.Book
	err := row.Scan(

		&res.ID,

		&res.Title,

		&res.Author,

		&res.Description,

		&res.CreatedAt,

		&res.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Book{}, ErrNotFound
		}
		return Book{}, err
	}

	// Convert to Domain Struct

	return Book{
		ID: res.ID,

		Title: res.Title,

		Author: res.Author,

		Description: res.Description,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetBookTags(ctx context.Context, bookID int64) ([]Tag, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetBookTags(ctx, bookID)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]Tag, len(res))
	for i, v := range res {
		items[i] = Tag{
			ID: v.ID,

			Name: v.Name,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetBooksByAuthor(ctx context.Context, author string) ([]Book, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetBooksByAuthor(ctx, author)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]Book, len(res))
	for i, v := range res {
		items[i] = Book{
			ID: v.ID,

			Title: v.Title,

			Author: v.Author,

			Description: v.Description,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) GetTag(ctx context.Context, id int64) (Tag, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.GetTag(ctx, id)
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Tag{}, ErrNotFound
		}

		return Tag{}, err
	}

	// Convert Single Domain Struct

	return Tag{
		ID: res.ID,

		Name: res.Name,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	query := "SELECT \"id\", \"name\", \"created_at\", \"updated_at\" FROM tags WHERE id = ?"
	row := w.adapter.DBTX().QueryRowContext(ctx, query, id)
	var res sqlitedb.Tag
	err := row.Scan(

		&res.ID,

		&res.Name,

		&res.CreatedAt,

		&res.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Tag{}, ErrNotFound
		}
		return Tag{}, err
	}

	// Convert to Domain Struct

	return Tag{
		ID: res.ID,

		Name: res.Name,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) ListBooks(ctx context.Context) ([]Book, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.ListBooks(ctx)
	if err != nil {
		return nil, err
	}

	// Convert Slice of Domain Structs
	items := make([]Book, len(res))
	for i, v := range res {
		items[i] = Book{
			ID: v.ID,

			Title: v.Title,

			Author: v.Author,

			Description: v.Description,

			CreatedAt: v.CreatedAt,

			UpdatedAt: v.UpdatedAt,
		}
	}
	return items, nil
}

func (w *sqliteWrapper) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	/* --- Auto-Loop for Bulk Insert on Non-Postgres --- */

	res, err := w.adapter.UpdateBook(ctx, sqlitedb.UpdateBookParams{
		Title:       arg.Title,
		Author:      arg.Author,
		Description: arg.Description,
		ID:          arg.ID,
	})
	if err != nil {

		if errors.Is(err, sql.ErrNoRows) {
			return Book{}, ErrNotFound
		}

		return Book{}, err
	}

	// Convert Single Domain Struct

	return Book{
		ID: res.ID,

		Title: res.Title,

		Author: res.Author,

		Description: res.Description,

		CreatedAt: res.CreatedAt,

		UpdatedAt: res.UpdatedAt,
	}, nil
}

func (w *sqliteWrapper) WithTx(tx *sql.Tx) Querier {
	res := w.adapter.WithTx(tx)
	return &sqliteWrapper{adapter: res}
}

func (w *sqliteWrapper) DB() *sql.DB {
	return w.adapter.DB()
}
