// Code generated by sqlc. DO NOT EDIT.

package postgresdb

import (
	"database/sql"
	"time"
)

type Book struct {
	ID          int64
	Title       string
	Author      string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
