// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"context"
)

type Querier interface {
	// INSERT INTO book_tags ("book_id", "tag_id") VALUES ($1, $2)
	//
	//  INSERT INTO book_tags ("book_id", "tag_id")
	//  VALUES ($1, $2)
	AddBookTag(ctx context.Context, arg AddBookTagParams) error
	// INSERT INTO book_tags ("book_id", "tag_id") VALUES (unnest($1::bigint[]), unnest($2::bigint[]))
	// @bulk-for AddBookTag
	//
	//  INSERT INTO book_tags ("book_id", "tag_id")
	//  VALUES (unnest($1::bigint[]), unnest($2::bigint[]))
	AddBookTags(ctx context.Context, arg AddBookTagsParams) error
	// INSERT INTO books ("title", "author", "description") VALUES ($1, $2, $3) RETURNING "id", "title", "author", "description", "created_at", "updated_at"
	//
	//  INSERT INTO books ("title", "author", "description")
	//  VALUES ($1, $2, $3)
	//  RETURNING "id", "title", "author", "description", "created_at", "updated_at"
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	// INSERT INTO tags ("name") VALUES ($1) RETURNING "id", "name", "created_at", "updated_at"
	//
	//  INSERT INTO tags ("name")
	//  VALUES ($1)
	//  RETURNING "id", "name", "created_at", "updated_at"
	CreateTag(ctx context.Context, name string) (Tag, error)
	// DELETE FROM books WHERE id = $1
	//
	//  DELETE FROM books
	//  WHERE id = $1
	DeleteBook(ctx context.Context, id int64) error
	// SELECT "id", "title", "author", "description", "created_at", "updated_at" FROM books WHERE id = $1
	//
	//  SELECT "id", "title", "author", "description", "created_at", "updated_at"
	//  FROM books
	//  WHERE id = $1
	GetBook(ctx context.Context, id int64) (Book, error)
	// SELECT t."id", t."name", t."created_at", t."updated_at" FROM tags t INNER JOIN book_tags bt ON t.id = bt.tag_id WHERE bt.book_id = $1
	//
	//  SELECT t."id", t."name", t."created_at", t."updated_at"
	//  FROM tags t
	//  INNER JOIN book_tags bt ON t.id = bt.tag_id
	//  WHERE bt.book_id = $1
	GetBookTags(ctx context.Context, bookID int64) ([]Tag, error)
	// SELECT "id", "title", "author", "description", "created_at", "updated_at" FROM books WHERE author = $1
	//
	//  SELECT "id", "title", "author", "description", "created_at", "updated_at"
	//  FROM books
	//  WHERE author = $1
	GetBooksByAuthor(ctx context.Context, author string) ([]Book, error)
	// SELECT "id", "name", "created_at", "updated_at" FROM tags WHERE id = $1
	//
	//  SELECT "id", "name", "created_at", "updated_at"
	//  FROM tags
	//  WHERE id = $1
	GetTag(ctx context.Context, id int64) (Tag, error)
	// SELECT "id", "title", "author", "description", "created_at", "updated_at" FROM books ORDER BY title
	//
	//  SELECT "id", "title", "author", "description", "created_at", "updated_at"
	//  FROM books
	//  ORDER BY title
	ListBooks(ctx context.Context) ([]Book, error)
	// UPDATE books SET "title" = $1, "author" = $2, "description" = $3, "updated_at" = NOW() WHERE id = $4 RETURNING "id", "title", "author", "description", "created_at", "updated_at"
	//
	//  UPDATE books
	//  SET "title" = $1,
	//      "author" = $2,
	//      "description" = $3,
	//      "updated_at" = NOW()
	//  WHERE id = $4
	//  RETURNING "id", "title", "author", "description", "created_at", "updated_at"
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
