// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysqldb

import (
	"database/sql"
	"time"
)

type Book struct {
	ID          int64
	Title       string
	Author      string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BookTag struct {
	BookID int64
	TagID  int64
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
