// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysqldb

import (
	"context"
	"database/sql"
)

type Querier interface {
	// INSERT INTO book_tags (`book_id`, `tag_id`) VALUES (?, ?)
	//
	//  INSERT INTO book_tags (`book_id`, `tag_id`)
	//  VALUES (?, ?)
	AddBookTag(ctx context.Context, arg AddBookTagParams) error
	// INSERT INTO book_tags (`book_id`, `tag_id`) VALUES (?, ?)
	// @bulk-for AddBookTag
	//
	//  INSERT INTO book_tags (`book_id`, `tag_id`)
	//  VALUES (?, ?)
	AddBookTags(ctx context.Context, arg AddBookTagsParams) error
	// INSERT INTO books (`title`, `author`, `description`) VALUES (?, ?, ?)
	//
	//  INSERT INTO books (`title`, `author`, `description`)
	//  VALUES (?, ?, ?)
	CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error)
	// INSERT INTO tags (`name`) VALUES (?)
	//
	//  INSERT INTO tags (`name`)
	//  VALUES (?)
	CreateTag(ctx context.Context, name string) (sql.Result, error)
	// DELETE FROM books WHERE id = ?
	//
	//  DELETE FROM books
	//  WHERE id = ?
	DeleteBook(ctx context.Context, id int64) error
	// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books WHERE id = ?
	//
	//  SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at`
	//  FROM books
	//  WHERE id = ?
	GetBook(ctx context.Context, id int64) (Book, error)
	// SELECT t.`id`, t.`name`, t.`created_at`, t.`updated_at` FROM tags t INNER JOIN book_tags bt ON t.id = bt.tag_id WHERE bt.book_id = ?
	//
	//  SELECT t.`id`, t.`name`, t.`created_at`, t.`updated_at`
	//  FROM tags t
	//  INNER JOIN book_tags bt ON t.id = bt.tag_id
	//  WHERE bt.book_id = ?
	GetBookTags(ctx context.Context, bookID int64) ([]Tag, error)
	// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books WHERE author = ?
	//
	//  SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at`
	//  FROM books
	//  WHERE `author` = ?
	GetBooksByAuthor(ctx context.Context, author string) ([]Book, error)
	// SELECT `id`, `name`, `created_at`, `updated_at` FROM tags WHERE id = ?
	//
	//  SELECT `id`, `name`, `created_at`, `updated_at`
	//  FROM tags
	//  WHERE id = ?
	GetTag(ctx context.Context, id int64) (Tag, error)
	// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books ORDER BY title
	//
	//  SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at`
	//  FROM books
	//  ORDER BY `title`
	ListBooks(ctx context.Context) ([]Book, error)
	// UPDATE books SET `title` = ?, `author` = ?, `description` = ?, `updated_at` = NOW() WHERE id = ?
	//
	//  UPDATE books
	//  SET `title` = ?,
	//      `author` = ?,
	//      `description` = ?,
	//      `updated_at` = NOW()
	//  WHERE id = ?
	UpdateBook(ctx context.Context, arg UpdateBookParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
