// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.mysql.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const addBookTag = `-- name: AddBookTag :exec
INSERT INTO book_tags (` + "`" + `book_id` + "`" + `, ` + "`" + `tag_id` + "`" + `)
VALUES (?, ?)
`

type AddBookTagParams struct {
	BookID int64
	TagID  int64
}

// INSERT INTO book_tags (`book_id`, `tag_id`) VALUES (?, ?)
//
//	INSERT INTO book_tags (`book_id`, `tag_id`)
//	VALUES (?, ?)
func (q *Queries) AddBookTag(ctx context.Context, arg AddBookTagParams) error {
	_, err := q.db.ExecContext(ctx, addBookTag, arg.BookID, arg.TagID)
	return err
}

const addBookTags = `-- name: AddBookTags :exec
INSERT INTO book_tags (` + "`" + `book_id` + "`" + `, ` + "`" + `tag_id` + "`" + `)
VALUES (?, ?)
`

type AddBookTagsParams struct {
	BookID int64
	TagID  int64
}

// INSERT INTO book_tags (`book_id`, `tag_id`) VALUES (?, ?)
// @bulk-for AddBookTag
//
//	INSERT INTO book_tags (`book_id`, `tag_id`)
//	VALUES (?, ?)
func (q *Queries) AddBookTags(ctx context.Context, arg AddBookTagsParams) error {
	_, err := q.db.ExecContext(ctx, addBookTags, arg.BookID, arg.TagID)
	return err
}

const createBook = `-- name: CreateBook :execresult
INSERT INTO books (` + "`" + `title` + "`" + `, ` + "`" + `author` + "`" + `, ` + "`" + `description` + "`" + `)
VALUES (?, ?, ?)
`

type CreateBookParams struct {
	Title       string
	Author      string
	Description sql.NullString
}

// INSERT INTO books (`title`, `author`, `description`) VALUES (?, ?, ?)
//
//	INSERT INTO books (`title`, `author`, `description`)
//	VALUES (?, ?, ?)
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBook, arg.Title, arg.Author, arg.Description)
}

const createTag = `-- name: CreateTag :execresult
INSERT INTO tags (` + "`" + `name` + "`" + `)
VALUES (?)
`

// INSERT INTO tags (`name`) VALUES (?)
//
//	INSERT INTO tags (`name`)
//	VALUES (?)
func (q *Queries) CreateTag(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTag, name)
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = ?
`

// DELETE FROM books WHERE id = ?
//
//	DELETE FROM books
//	WHERE id = ?
func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT ` + "`" + `id` + "`" + `, ` + "`" + `title` + "`" + `, ` + "`" + `author` + "`" + `, ` + "`" + `description` + "`" + `, ` + "`" + `created_at` + "`" + `, ` + "`" + `updated_at` + "`" + `
FROM books
WHERE id = ?
`

// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books WHERE id = ?
//
//	SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at`
//	FROM books
//	WHERE id = ?
func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookTags = `-- name: GetBookTags :many
SELECT t.` + "`" + `id` + "`" + `, t.` + "`" + `name` + "`" + `, t.` + "`" + `created_at` + "`" + `, t.` + "`" + `updated_at` + "`" + `
FROM tags t
INNER JOIN book_tags bt ON t.id = bt.tag_id
WHERE bt.book_id = ?
`

// SELECT t.`id`, t.`name`, t.`created_at`, t.`updated_at` FROM tags t INNER JOIN book_tags bt ON t.id = bt.tag_id WHERE bt.book_id = ?
//
//	SELECT t.`id`, t.`name`, t.`created_at`, t.`updated_at`
//	FROM tags t
//	INNER JOIN book_tags bt ON t.id = bt.tag_id
//	WHERE bt.book_id = ?
func (q *Queries) GetBookTags(ctx context.Context, bookID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getBookTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT ` + "`" + `id` + "`" + `, ` + "`" + `title` + "`" + `, ` + "`" + `author` + "`" + `, ` + "`" + `description` + "`" + `, ` + "`" + `created_at` + "`" + `, ` + "`" + `updated_at` + "`" + `
FROM books
WHERE ` + "`" + `author` + "`" + ` = ?
`

// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books WHERE author = ?
//
//	SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at`
//	FROM books
//	WHERE `author` = ?
func (q *Queries) GetBooksByAuthor(ctx context.Context, author string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthor, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT ` + "`" + `id` + "`" + `, ` + "`" + `name` + "`" + `, ` + "`" + `created_at` + "`" + `, ` + "`" + `updated_at` + "`" + `
FROM tags
WHERE id = ?
`

// SELECT `id`, `name`, `created_at`, `updated_at` FROM tags WHERE id = ?
//
//	SELECT `id`, `name`, `created_at`, `updated_at`
//	FROM tags
//	WHERE id = ?
func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT ` + "`" + `id` + "`" + `, ` + "`" + `title` + "`" + `, ` + "`" + `author` + "`" + `, ` + "`" + `description` + "`" + `, ` + "`" + `created_at` + "`" + `, ` + "`" + `updated_at` + "`" + `
FROM books
ORDER BY ` + "`" + `title` + "`" + `
`

// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books ORDER BY title
//
//	SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at`
//	FROM books
//	ORDER BY `title`
func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :execresult
UPDATE books
SET ` + "`" + `title` + "`" + ` = ?,
    ` + "`" + `author` + "`" + ` = ?,
    ` + "`" + `description` + "`" + ` = ?,
    ` + "`" + `updated_at` + "`" + ` = NOW()
WHERE id = ?
`

type UpdateBookParams struct {
	Title       string
	Author      string
	Description sql.NullString
	ID          int64
}

// UPDATE books SET `title` = ?, `author` = ?, `description` = ?, `updated_at` = NOW() WHERE id = ?
//
//	UPDATE books
//	SET `title` = ?,
//	    `author` = ?,
//	    `description` = ?,
//	    `updated_at` = NOW()
//	WHERE id = ?
func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBook,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.ID,
	)
}
