// Code generated by sqlc. DO NOT EDIT.

package mysqldb

import (
	"context"
	"database/sql"
)

type Querier interface {
	// AddBookTag adds a tag to a book.
	// INSERT INTO book_tags (`book_id`, `tag_id`) VALUES (?, ?)
	AddBookTag(ctx context.Context, arg AddBookTagParams) error

	// AddBookTags adds multiple tags to a book.
	// INSERT INTO book_tags (`book_id`, `tag_id`) VALUES (?, ?)
	// @bulk-for AddBookTag
	AddBookTags(ctx context.Context, arg AddBookTagsParams) error

	// CreateBook creates a new book.
	// INSERT INTO books (`title`, `author`, `description`) VALUES (?, ?, ?)
	CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error)

	// CreateTag creates a new tag.
	// INSERT INTO tags (`name`) VALUES (?)
	CreateTag(ctx context.Context, name string) (sql.Result, error)

	// DeleteBook deletes a book by ID.
	// DELETE FROM books WHERE id = ?
	DeleteBook(ctx context.Context, id int64) error

	// GetBook retrieves a book by ID.
	// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books WHERE id = ?
	GetBook(ctx context.Context, id int64) (Book, error)

	// GetBookTags retrieves all tags for a book.
	// SELECT t.`id`, t.`name`, t.`created_at`, t.`updated_at` FROM tags t INNER JOIN book_tags bt ON t.id = bt.tag_id WHERE bt.book_id = ?
	GetBookTags(ctx context.Context, bookID int64) ([]Tag, error)

	// GetBooksByAuthor retrieves all books by an author.
	// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books WHERE author = ?
	GetBooksByAuthor(ctx context.Context, author string) ([]Book, error)

	// GetTag retrieves a tag by ID.
	// SELECT `id`, `name`, `created_at`, `updated_at` FROM tags WHERE id = ?
	GetTag(ctx context.Context, id int64) (Tag, error)

	// ListBooks retrieves all books.
	// SELECT `id`, `title`, `author`, `description`, `created_at`, `updated_at` FROM books ORDER BY title
	ListBooks(ctx context.Context) ([]Book, error)

	// UpdateBook updates a book.
	// UPDATE books SET `title` = ?, `author` = ?, `description` = ?, `updated_at` = NOW() WHERE id = ?
	UpdateBook(ctx context.Context, arg UpdateBookParams) (sql.Result, error)
}
